### ISSUE TITLE
Namespacing suggestion

### ISSUE THREAD

**Issue by pkrefta** [freego/capistrano-thin#5]
Hey,

Most of ruby application servers is using their name as namespace - e.g. **unicorn:start** etc. Is it possible to gradually change namespace to **thin** ? **deploy** is used mostly for Capistrano tasks such as **deploy:rollback** and it's little bit confusing to use **deploy:start** etc. What do you guys think ? I'll issue pull request if that's OK :)

**Comment by alepore** [comment]
sure, `deploy:start` is legacy stuff from capistrano 2, `thin:start` would be better, please go for it :)

**Comment by pkrefta** [comment]
I'll issue pull request later today.

**Comment by pkrefta** [comment]
Sent & merged :)
